(()=>{'use strict';
const API='https://hk-license.89.125.1.71.sslip.io/api/v1/cabinet/contest/';
const token=localStorage.getItem('tk_clan_contest_session')||localStorage.getItem('tk_clan_cabinet_session')||'';
const content=document.getElementById('content'),notice=document.getElementById('notice');
const escape=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let cache={},kind='items';
async function open(next){kind=next;notice.textContent='Загрузка…';try{if(!cache[kind]){const r=await fetch(API+'material',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({kind})});const d=await r.json();if(!r.ok)throw Error('Материалы доступны владельцу в закрытом режиме, участникам — после открытия конкурса. Войдите на вкладке «Конкурс».');cache[kind]=d.material;}notice.textContent='';render();}catch(e){notice.textContent=e.message;content.textContent='';}}
function render(){if(kind==='map'){map(cache.map);return;}const rows=cache[kind].slice().sort((a,b)=>a.name.localeCompare(b.name,'ru'));content.innerHTML='<label>Поиск<input id="search" placeholder="Название, описание или бонус"></label><div id="cards"></div>';const draw=()=>{const q=document.getElementById('search').value.toLowerCase();document.getElementById('cards').innerHTML=rows.filter(x=>JSON.stringify(x).toLowerCase().includes(q)).map(x=>`<article class="card"><h2>${escape(x.name)}</h2><p>${escape(x.rarity||'')} ${x.tier?' · тир '+escape(x.tier):''}</p><p>${escape(x.description)}</p>${x.note?'<h3>Конкурсная записка</h3><p>'+escape(x.note)+'</p>':''}${x.bonuses?'<ul>'+x.bonuses.map(b=>'<li>'+escape(b.caption)+': '+escape(b.value)+'</li>').join('')+'</ul>':''}${x.components?'<h3>Компоненты</h3>'+x.components.map(c=>'<p>'+escape(c.name)+'</p><ul>'+(c.bonuses||[]).map(b=>'<li>'+escape(b.caption)+': '+escape(b.value)+'</li>').join('')+'</ul>').join(''):''}</article>`).join('');};document.getElementById('search').addEventListener('input',draw);draw();}
function map(data){const fs=data.full.buildings.features.filter(f=>f.properties.is_game),bounds=data.full.bounds;const x=lng=>(lng-bounds[0][0])/(bounds[1][0]-bounds[0][0])*1000,y=lat=>(bounds[1][1]-lat)/(bounds[1][1]-bounds[0][1])*850;const center=f=>{const ring=f.geometry.coordinates[0];return [(Math.min(...ring.map(p=>p[0]))+Math.max(...ring.map(p=>p[0])))/2,(Math.min(...ring.map(p=>p[1]))+Math.max(...ring.map(p=>p[1])))/2];};const colors={0:'#ff5c5c',1:'#ffd84a',2:'#ff9a3d',3:'#c238ff',4:'#35e875'};
content.innerHTML='<h2>Токио 25:12</h2><p>Север — сверху. Нажмите на точку здания, чтобы увидеть ID. Центр здания — центр охватывающего его прямоугольника.</p><label>Показать <select id="filter"><option value="all">Все здания</option>'+[1,2,3,4].map(k=>'<option value="'+k+'">'+k+' крист.</option>').join('')+'</select></label><p id="selected" role="status"></p><div style="overflow:auto;max-height:75vh"><svg id="map-svg" viewBox="0 0 1000 850" style="min-width:700px;width:100%;background:#242528" aria-label="Конкурсная карта"></svg></div>';const svg=document.getElementById('map-svg');let anchor=null;
const draw=()=>{const filter=document.getElementById('filter').value;svg.innerHTML=fs.map(f=>{const c=center(f),k=String(f.properties.crystals_key),shown=filter==='all'||filter===k;return '<polygon points="'+f.geometry.coordinates[0].map(p=>x(p[0])+','+y(p[1])).join(' ')+'" fill="'+escape(f.properties.base_color||'#555')+'" opacity="'+(shown?'.6':'.15')+'"/>'+(shown?'<circle data-id="'+escape(f.id)+'" cx="'+x(c[0])+'" cy="'+y(c[1])+'" r="4" fill="'+(colors[k]||'#aaa')+'"><title>'+escape(f.id)+' · '+k+' крист.</title></circle>':'');}).join('')+(anchor?'<path d="M0 '+y(anchor[1])+' H1000 M'+x(anchor[0])+' 0 V850" stroke="white" stroke-width="1.5" stroke-dasharray="6 4" pointer-events="none"/>':'');};svg.addEventListener('click',e=>{const id=e.target.dataset.id;if(!id)return;const f=fs.find(f=>f.id===id);document.getElementById('selected').textContent=id+' · '+f.properties.crystals_key+' крист.';if(f.properties.crystals_key==='4'){anchor=center(f);draw();}});document.getElementById('filter').addEventListener('change',draw);draw();}
document.querySelectorAll('[data-kind]').forEach(b=>b.addEventListener('click',()=>open(b.dataset.kind)));open('items');
})();
