from pathlib import Path
p=Path('/tmp/HamsterKingMobile.user.js')
s=p.read_text(encoding='utf-8')
MARK="const HK_PITS_REWARD_PICKER_REV = 'pits-reward-picker-20260920-r20';"
if MARK not in s: raise SystemExit('r20 marker missing')
anchor=".hk-pit-shared-grid strong{display:block;margin-top:2px;font-size:10px}"
css=".hk-pit-reward-controls button[data-pit-reward-open]{width:100%;min-height:34px;margin-top:4px;text-align:left}.hk-pit-reward-picker-overlay{position:fixed;inset:0;z-index:270;display:grid;place-items:center;padding:16px;background:#05080ddd;backdrop-filter:blur(8px)}.hk-pit-reward-picker-card{width:min(720px,100%);max-height:calc(100vh - 32px);overflow:auto;padding:14px;border:1px solid #ffad1f;border-radius:16px;background:linear-gradient(145deg,#171d28,#0d131d);box-shadow:0 22px 70px #000c}.hk-pit-reward-picker-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.hk-pit-reward-picker-head small{color:#ffcf73;font-weight:800}.hk-pit-reward-picker-head h3{margin:3px 0 0}.hk-pit-reward-picker-live{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}.hk-pit-reward-picker-live span{padding:7px 9px;border-radius:9px;background:#111a27;color:#8fa1b8;font-size:10px}.hk-pit-reward-picker-warning{padding:8px;margin-bottom:8px;border-radius:9px;background:#392c13;color:#ffd166;font-size:10px}.hk-pit-reward-picker-list{display:grid;gap:8px}.hk-pit-reward-card{display:grid;gap:8px;width:100%;padding:10px;text-align:left;border:1px solid #34455e;border-radius:12px;background:#0c1420}.hk-pit-reward-card.selected{border-color:#ffad1f;box-shadow:0 0 0 2px #ffad1f22}.hk-pit-reward-card:disabled{opacity:.52}.hk-pit-reward-card-top{display:flex;align-items:center;justify-content:space-between;gap:8px}.hk-pit-reward-card-top>strong{font-size:14px;color:#ffe083}.hk-pit-reward-card-top>div{display:flex;gap:5px;flex-wrap:wrap}.hk-pit-reward-entry{display:flex;align-items:center;gap:3px;padding:3px 5px;border-radius:7px;background:#172234}.hk-pit-reward-entry img{width:24px;height:24px;object-fit:contain}.hk-pit-reward-entry b{font-size:9px}.hk-pit-reward-card-meta{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:5px}.hk-pit-reward-card-meta span{padding:6px;border-radius:8px;background:#111a27}.hk-pit-reward-card-meta small{display:block;color:#8192a8;font-size:8px}.hk-pit-reward-card-meta b{display:block;margin-top:2px;font-size:10px}.hk-pit-reward-card-status{padding:6px 7px;border-radius:8px;font-size:9px}.hk-pit-reward-card-status.good{background:#153524;color:#7fe0ad}.hk-pit-reward-card-status.warn{background:#392c13;color:#ffd166}.hk-pit-reward-picker-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}@media(max-width:560px){.hk-pit-reward-card-meta{grid-template-columns:repeat(2,minmax(0,1fr))}}"
if anchor not in s: raise SystemExit('picker css anchor missing')
s=s.replace(anchor,anchor+css,1)
for x in [".hk-pit-reward-picker-overlay",".hk-pit-reward-card","button[data-pit-reward-open]"]:
    if x not in s: raise SystemExit('missing r20c invariant: '+x)
p.write_text(s,encoding='utf-8')
print('PITS_REWARD_PICKER_R20C_OK')
