"""Provision owner-only draft in an isolated database; never print answers or identities."""
import json
import os
from pathlib import Path
import re
import sqlite3
import subprocess
import sys
sys.path.insert(0,'/opt/hamsterking-license')
from contest_runtime import Contest

owner=sys.argv[1]
assert re.fullmatch(r'[1-9][0-9]{4,19}',owner),'Invalid owner ID'
pid=subprocess.check_output(['systemctl','show','hamsterking-license.service','-p','MainPID','--value'],text=True).strip()
process=Path('/proc/'+pid)
uid=process.stat().st_uid;gid=process.stat().st_gid
env=dict(x.split(b'=',1) for x in (process/'environ').read_bytes().split(b'\0') if b'=' in x)
main_db=env.get(b'HK_LICENSE_DB',b'/var/lib/hamsterking-license/licenses.db').decode()
path=Path(main_db).parent/'contest.db'
c=Contest(path,'provision-only',lambda _:None,lambda _:None)
with c.db() as db:
    cfg=c.config(db)
    assert not cfg['owner_id'] or cfg['owner_id']==owner,'Owner mismatch; refuse reassignment'
    cfg['owner_id']=owner
    # Actual answers are generated by the running service under its own signing key.
    # They never enter the repository, workflow inputs, or logs.
    db.execute('UPDATE settings SET value=? WHERE id=1',(json.dumps(cfg),))
os.chown(path,uid,gid);os.chmod(path,0o600)
print('CONTEST_OWNER_PROVISIONED=PASS; draft mode; separate database')
